image: "python:3.8"

cache:
  paths:
    - .pip-cache

before_script:
  - mkdir -p .pip-cache
  - pip install -U pip
  - pip --cache-dir=.pip-cache install flake8
  - pip --cache-dir=.pip-cache install pylint
  - pip install -r requirements.txt

stages:
  - Static Analysis
  - Unit Test
  - Installation Test

flake8:
  stage: Static Analysis
  script:
    - flake8 nebixbm/

pylint:
  stage: Static Analysis
  allow_failure: true
  script:
    - pylint nebixbm/ -d C0114

unittest:
  stage: Unit Test
  script:
    - python -m unittest discover nebixbm/

install_test:
  stage: Installation Test
  script:
    - pip install .
