version: "3.6"
services:

  nebixbm:
    depends_on:
      - redis_db
    build: .
    command: >
      bash -c "python nebixbm/database/wait_for_db.py; while true; do sleep 3000; done"

    image: nebixbm:v3
    environment:
      NEBIXBM_FILES: ${NEBIXBM_FILES}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASS: ${REDIS_PASS}
      NOTIFY_EMAIL: ${NOTIFY_EMAIL}
      NOTIFY_PASS: ${NOTIFY_PASS}
      EMAIL_SMTP_HOST: ${EMAIL_SMTP_HOST}
    tty: true
    volumes:
      -  ~/logfiles/:/usr/local/lib/python3.8/site-packages/nebixbm/log/logfiles

  redis_db:
    image: redis
    restart: always
    volumes:
      -  ~/redis-data/:/data
      -  ~/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - '127.0.0.1:6379:6379'
