version: "3.6"
services:
  nebixbm:
    depends_on:
      - redis_db
    build: .
    command: >
      bash -c "python nebixbm/database/wait_for_db.py; while true; do sleep 3000; done"
    networks:
      - shared-network
      ports:
        - "465:465"
    image: nebixbm:v2
    environment:
      NEBIXBM_FILES: ${NEBIXBM_FILES}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASS: ${REDIS_PASS}
      NOTIFY_EMAIL: ${NOTIFY_EMAIL}
      NOTIFY_PASS: ${NOTIFY_PASS}
      EMAIL_SMTP_HOST: ${EMAIL_SMTP_HOST}
    tty: true
    volumes:
      -  /docker-backup/logfiles:/usr/local/lib/python3.8/site-packages/nebixbm/log/logfiles
  redis-gui:
    depends_on:
      - redis_db
    build:
      context: .
      dockerfile: Dockerfile.redsmin
    restart: always
    networks:
      - shared-network
    image: redis-gui
    environment:
      REDSMIN_KEY: ${REDSMIN_KEY}
      REDIS_URI: "redis://172.20.0.6:6379"
  redis_db:
    image: redis
    restart: always
    networks:
      shared-network:
        ipv4_address: 172.20.0.6
    # ports:
    #   - "6379:6379"
    volumes:
      -  /docker-backup/docker-files/redis_data:/data

networks:
  shared-network:
    ipam:
      config:
        - subnet: 172.20.0.0/24
