version: "3.6"
services:

  nebixbm:
    depends_on:
      - redis_db
    build: .
    command: >
      bash -c "python nebixbm/database/wait_for_db.py; while true; do sleep 3000; done"
    networks:
      - shared-network
    image: nebixbm:v3
    environment:
      NEBIXBM_FILES: ${NEBIXBM_FILES}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASS: ${REDIS_PASS}
      NOTIFY_EMAIL: ${NOTIFY_EMAIL}
      NOTIFY_PASS: ${NOTIFY_PASS}
      EMAIL_SMTP_HOST: ${EMAIL_SMTP_HOST}
    tty: true
    volumes:
      -  ${pwd}/neb-files/logfiles/:/usr/local/lib/python3.8/site-packages/nebixbm/log/logfiles

  redis_db:
    image: redis
    restart: always
    volumes:
      -  ${pwd}/neb-files/redis-data/data/:/data
      -  ${pwd}/neb-files/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      -  6379:6379
    networks:
      shared-network:
        ipv4_address: ${REDIS_HOST}

networks:
  shared-network:
    ipam:
      config:
        - subnet: 172.20.0.0/24
