version: "3.6"
services:
  nebixbm:
    depends_on:
      - redis_db
    build: .
    command: python /database/wait_for_db.py
    networks:
      - shared-network
    image: nebixbm:v2
    tty: true
    volumes:
      -  ~/Desktop/docker-files/logfiles:/nebix/nebix-trading-bot/env/lib/python3.8/site-packages/nebixbm/log/logfiles

  redis_db:
    image: redis
    restart: always
    networks:
      - shared-network
    ports:
      - "6379:6379"
    volumes:
      -  ~/Desktop/docker-files/redis_data:/data

networks:
  shared-network: {}
