version: "3.6"
services:

  nebixbm:
    depends_on:
      - redis_db
    build: .
    command: >
      bash -c "python nebixbm/database/wait_for_db.py; while true; do sleep 3000; done"
    networks:
      - backend
    image: nebixbm:v3
    environment:
      NEBIXBM_FILES: ${NEBIXBM_FILES}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASS: ${REDIS_PASS}
      NOTIFY_EMAIL: ${NOTIFY_EMAIL}
      NOTIFY_PASS: ${NOTIFY_PASS}
      EMAIL_SMTP_HOST: ${EMAIL_SMTP_HOST}
      NOTIFY_TELEGRAM_TOKEN: ${NOTIFY_TELEGRAM_TOKEN}
      NOTIFY_TELEGRAM_ID: ${NOTIFY_TELEGRAM_ID}
      BYBIT_TEST_SECRET: ${BYBIT_TEST_SECRET}
      BYBIT_TEST_APIKEY: ${BYBIT_TEST_APIKEY}
      BYBIT_MAIN_SECRET: ${BYBIT_MAIN_SECRET}
      BYBIT_MAIN_APIKEY: ${BYBIT_MAIN_APIKEY}
      BINANCE_TEST_SECRET: ${BINANCE_TEST_SECRET}
      BINANCE_TEST_APIKEY: ${BINANCE_TEST_APIKEY}
    tty: true
    volumes:
      -  ~/logfiles/:/usr/local/lib/python3.8/site-packages/nebixbm/log/logfiles

  redis_db:
    image: redis
    restart: always
    volumes:
      -  ~/redis-data/:/data
    networks:
      backend:
        ipv4_address: ${REDIS_HOST}
      db-gui:
        ipv4_address: 178.0.0.11

  redis-gui:
    depends_on:
      - redis_db
    build:
      context: .
      dockerfile: Dockerfile.redsmin
    networks:
      - db-gui
    restart: always
    image: redis-gui
    environment:
      REDSMIN_KEY: ${REDSMIN_KEY}
      REDIS_URI: "redis://178.0.0.11:6379"

networks:
  backend:
    ipam:
      config:
        - subnet: 177.0.0.0/24
  db-gui:
    ipam:
      config:
        - subnet: 178.0.0.0/24
